<?php

namespace App\Permission;

class PermissionConst
{
    // const GESTION_MENU = 'gestion_menu';

    const GESTION_TIPO_CONTRATO = 'GESTION_TIPO_CONTRATO';
    const GESTION_ROLES = 'GESTION_ROLES';
    const GESTION_ROL_PERMISOS = 'GESTION_ROL_PERMISOS';
    const GESTION_USUARIO = 'GESTION_USUARIO';
    const GESTION_PROCESOS = 'GESTION_PROCESOS';
    const GESTION_TIPO_DOCUMENTOS = 'GESTION_TIPO_DOCUMENTOS';
    const GESTION_MEDIO_PAGO = 'GESTION_MEDIO_PAGO';
    const GESTION_TIPO_PAGO = 'GESTION_TIPO_PAGO';
    const GESTION_TIPO_TRANSACCION = 'GESTION_TIPO_TRANSACCION';
    const GESTION_COMPETENCIAS = 'GESTION_COMPETENCIAS';

}
